services:
  jenkins:
    image: 026090544275.dkr.ecr.ap-northeast-2.amazonaws.com/iac:latest
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
